
#define MAJOR_VERSION "@MAJOR_VERSION@"
#define MINOR_VERSION "@MINOR_VERSION@"
#define MICRO_VERSION "@MICRO_VERSION@"
#define VERSION "@MAJOR_VERSION@.@MINOR_VERSION@.@MICRO_VERSION@"
#define __STATIC static
